version: '3'
services:
  app:
    container_name: released_notifier
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./lis_notifier.log:/app/lis_notifier.log
    entrypoint: ["/app/main"]