version: '3'
services:
  app:
    container_name: rel_not
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./lis_notifier.log:/app/lis_notifier.log
      - /mnt/busse/it/qc_db:/app/qc_db
    entrypoint: ["/app/main"]